name: notes_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_navigation: ^0.0.7
  collection: ^1.16.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  flutter_staggered_grid_view: ^0.6.1
  gap: ^2.0.0
  go_router: ^3.1.1
  notes_common:
    path: ../packages/notes_common
  riverpod: ^2.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
