name: notes_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  faker: ^2.0.0
  notes_common:
    path: ../packages/notes_common

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
