name: chapter_1
description: An enhanced counter app built in the first chapter.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.5.0

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.4

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  golden_toolkit: ^0.10.0

flutter:
  uses-material-design: true